TRIAL_SUBSCRIBE_DAYS = 7     # время жизни trial подписки в днях
MAX_ORDERS_CNT = 5      # макс количество счетов у одного пользователя
SUB_DAYS_LEFT = [7, 3, 1]
PENDING_ORDER_TTL = 3
PENDING_ORDER_NOTIFICATION = 1
LEN_PROMOCODE = 6
DISCOUNT_FOR_INVITE = 100
DISCOUNT_FOR_NEW_USER = 300
MAX_DISCOUNT = 800

